package com.fooddelivery.notifications;

public enum EventType {
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_PREPARING,
    ORDER_READY,
    ORDER_ASSIGNED,
    ORDER_ACCEPTED,
    ORDER_REJECTED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED
}
